services:
  - type: web
    name: digikavach-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
